export const CLEAR_ACTIVITY_LIST_SEARCH = 'CLEAR_ACTIVITY_LIST_SEARCH'
export const CLEAR_ACTIVITY_LIST_TABLE = 'CLEAR_ACTIVITY_LIST_TABLE'
export const CLEAR_AUTHENTICATION = 'CLEAR_AUTHENTICATION'
export const CLEAR_BREAD = 'CLEAR_BREAD'
export const CLEAR_BUSINESS_LINE = 'CLEAR_BUSINESS_LINE'
export const CLEAR_CREATE_ACTION = 'CLEAR_CREATE_ACTION'
export const CLEAR_HEADER = 'CLEAR_HEADER'
export const CLEAR_LOADING = 'CLEAR_LOADING'
export const CLEAR_LOGIN = 'CLEAR_LOGIN'
export const CLEAR_PASSWORD = 'CLEAR_PASSWORD'
export const CLEAR_RESET_PASSWORD = 'CLEAR_RESET_PASSWORD'
export const CLEAR_SIDER_MENU = 'CLEAR_SIDER_MENU'
export const CLEAR_STATISTICS = 'CLEAR_STATISTICS'
export const CLEAR_UPDATE_PASSWORD = 'CLEAR_UPDATE_PASSWORD'

export const CHANGE_BREAD_NAV = 'CHANGE_BREAD_NAV' //切换面包屑
export const START_LOADING = 'START_LOADING' //开始loading
export const STOP_LOADING = 'STOP_LOADING' //结束loading


export const CHANGE_STEP = 'CHANGE_STEP' //更改创建活动步骤

export const CREATE_ACTION_CONFIRM = 'CREATE_ACTION_CONFIRM' // 创建活动确认

export const CREATE_ACTION_SKIP = 'CREATE_ACTION_SKIP' //创建活动跳过

export const CHANGE_CREATE_ACT_INFO = 'CHANGE_CREATE_ACT_INFO' //修改创建活动信息

export const SET_CREATE_ACT_ID = 'SET_CREATE_ACT_ID' //设置创建活动ID


export const CLEAN_ACT_SIGN_SHORT_URL = 'CLEAN_ACT_SIGN_SHORT_URL' //清空第三步的短链接
export const SET_STEP3_CAN_GO = 'SET_STEP3_CAN_GO' // 设置第三步是否可离开创建活动页面

export const CREATE_ACTION_COMPLETE = 'CREATE_ACTION_COMPLETE' //创建活动完成

export const SET_TAGS = 'SET_TAGS' //设置标签一级下拉
export const SET_UNFORMAT_TAGS = 'SET_UNFORMAT_TAGS' //设置未整理成树得标签
export const SET_LOGIC_COUNT = 'SET_LOGIC_COUNT' //设置ES逻辑得条数
export const CHANGE_ES = 'CHANGE_ES' //修改ES表达式
export const CLEAN_CALCU_RESULT = 'CLEAN_CALCU_RESULT'//清除计算活动人群

export const CLEAN_CREATE_ACT_INFO = 'CLEAN_CREATE_ACT_INFO' //清空创建活动信息

export const SET_ACT_AUDIT_EMAILS = 'SET_ACT_AUDIT_EMAILS' //设置发送邮箱
export const SET_DEFAULT_EMAIL = 'SET_DEFAULT_EMAIL' //设置默认邮箱


export const CHANGE_PASSWORD_SHOW_MODAL = 'CHANGE_PASSWORD_SHOW_MODAL' // 改变密码框实现隐藏
export const CHANGE_PASS_ACTION = 'CHANGE_PASS_ACTION' // 改变密码框类型


export const CHANGE_HEADER_SHOW_MODAL = 'CHANGE_HEADER_SHOW_MODAL' // 设置header弹框 显示隐藏

export const SET_MY_BUSINESS_LINE = 'SET_MY_BUSINESS_LINE' // 设置header弹框内容 业务线信息
export const SET_BL_QUERY_PARAMS = 'SET_BL_QUERY_PARAMS' // 设置业务线管理页面查询参数
export const SET_CREATE_BL_INFO = 'SET_CREATE_BL_INFO' //  设置创建业务线数据
export const SET_BL_OPERATE_RECORDS = 'SET_BL_OPERATE_RECORDS' //  设置业务线操作记录


export const SET_ACTIVITY_USER_INFO = 'SET_ACTIVITY_USER_INFO' //活动用户明细
export const SET_ACTIVITY_USER_INFO_TOTAL = 'SET_ACTIVITY_USER_INFO_TOTAL' //活动用户明细总条数


export const SET_ACTIVITY_STATISTICS = 'SET_ACTIVITY_STATISTICS' //活动转化明细
export const SET_ACTIVITY_STATISTICS_TOTAL = 'SET_ACTIVITY_STATISTICS_TOTAL' //活动转化明细总条数


// export const CHANGE_EDIT_STEP = 'CHANGE_EDIT_STEP' //更改编辑活动步骤

// export const EDIT_ACTION_CONFIRM = 'EDIT_ACTION_CONFIRM' //编辑活动确认

// export const CHANGE_EIDT_ACT_INFO = 'CHANGE_EIDT_ACT_INFO' //添加编辑活动信息


export const SET_USERNAME = 'SET_USERNAME'
export const SET_PASSWORD = 'SET_PASSWORD'
export const SET_CAPTCHA = 'SET_CAPTCHA'
export const SET_CAPTCHA_BASE64 = 'SET_CAPTCHA_BASE64'
export const SET_CAPTCHA_KEY = 'SET_CAPTCHA_KEY'
export const SET_USERNAME_CORRECT = 'SET_USERNAME_CORRECT'
export const SET_PASSWORD_CORRECT = 'SET_PASSWORD_CORRECT'
export const SET_CAPTCHA_CORRECT = 'SET_CAPTCHA_CORRECT'
export const SET_CAPTCHA_ERR_MSG = 'SET_CAPTCHA_ERR_MSG'
export const UPDATE_LOGIN = 'UPDATE_LOGIN'

export const SET_RESOURCES = 'SET_RESOURCES'
export const SET_ROLES = 'SET_ROLES'
export const SET_USER = 'SET_USER'

export const SET_SIDER_MENU = 'SET_SIDER_MENU'

export const RESET_PASSWORD_VISIBLE = 'RESET_PASSWORD_VISIBLE'
export const RET_USER_NAME_IN_RESET = 'RET_USER_NAME_IN_RESET'
export const SET_USER_NAME_CORRECT_IN_RESET = 'SET_USER_NAME_CORRECT_IN_RESET'
export const SET_NAME_IN_RESET = 'SET_NAME_IN_RESET'
export const SET_NAME_CORRECT_IN_RESET = 'SET_NAME_CORRECT_IN_RESET'
export const SET_RESET_PASSWORD = 'SET_RESET_PASSWORD'

export const SET_UPDATE_PASSWORD_VISIBLE = 'SET_UPDATE_PASSWORD_VISIBLE'
export const SET_NEW_PASSWORD = 'SET_NEW_PASSWORD'
export const SET_NEW_PASSWORD_CORRECT = 'SET_NEW_PASSWORD_CORRECT'
export const SET_NEW_PASSWORD_AGAIN = 'SET_NEW_PASSWORD_AGAIN'
export const SET_NEW_PASSWORD_AGAIN_CORRECT = 'SET_NEW_PASSWORD_AGAIN_CORRECT'
export const SET_UPDATE_PASSWORD = 'SET_UPDATE_PASSWORD'


// 设置 运营活动列表 页查询区已选择的查询条件
export const SET_ACTIVITY_LIST_SEARCH_DICTS = 'SET_ACTIVITY_LIST_SEARCH_DICTS'
export const SET_ACTIVITY_LIST_SEARCH_SELECTED = 'SET_ACTIVITY_LIST_SEARCH_SELECTED'
export const SET_ACTIVITY_LIST_SEARCH_SELECTED_IN_REAL_SEARCH = 'SET_ACTIVITY_LIST_SEARCH_SELECTED_IN_REAL_SEARCH'
export const SET_ACTIVITY_LIST_TABLE_RECORDS = 'SET_ACTIVITY_LIST_TABLE_RECORDS'
export const SET_ACTIVITY_LIST_TABLE_PAGINATION = 'SET_ACTIVITY_LIST_TABLE_PAGINATION'
export const SET_ACTIVITY_LIST_TABLE_PAGINATION_CURRENT_PAGE = 'SET_ACTIVITY_LIST_TABLE_PAGINATION_CURRENT_PAGE'


//设置用户转化查询条件
export const SET_AUI_QUERY = "SET_AUI_QUERY"
export const SET_AT_QUERY = "SET_AT_QUERY"


// 用户查询信息
export const SET_USER_QUERY_INFO = 'SET_USER_QUERY_INFO'

//创建页面右侧数据

export const ALL_TEMPLATE = "ALL_TEMPLATE"
export const SET_TEMPLATE_DATE = "SET_TEMPLATE_DATE"
export const CLEAR_TEMPLATE_DATE = "CLEAR_TEMPLATE_DATE"
export const SET_PAGE_COMPONENTS = "SET_PAGE_COMPONENTS"

// 拖拽测试
export const SET_PAGE_CONFIG_ARR = "SET_PAGE_CONFIG_ARR"
export const SET_PAGE = "SET_PAGE"
export const CLEAR_PAGE_CONFIG_ARR = "CLEAR_PAGE_CONFIG_ARR"

// 查询页面转化报表数据
export const SET_PAGE_TRANSFORMATION = 'SET_PAGE_TRANSFORMATION'

// 查询活动页面管理
export const SET_PAGE_ACTIVITY_PARAMES = 'SET_PAGE_ACTIVITY_PARAMES'
// 清空活动页面数据
export const CLEARN_PAGE_ACTIVITY = 'CLEARN_PAGE_ACTIVITY'
export const CLEARN_USER_INFO = 'CLEARN_USER_INFO'
export const CLEARN_PAGETRANSFORMATION = 'CLEARN_PAGETRANSFORMATION'
